In [1]:
import pandas as pd

import numpy as np

In [18]:
df = pd.read_excel(r'C:\Users\Samyak\OneDrive\Documents\Data Analysis Projects\Project-2(Ola)\Ola.xlsx')
df.head()

,Date,Booking_Status,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
0,26-07-2024,Canceled by Driver,Prime Sedan,Tumkur Road,RT Nagar,0,0,NaN,Personal & Car related issue,NaN,NaN,444.0,NaN,0.0,NaN,NaN
1,25-07-2024,Success,Bike,Magadi Road,Varthur,203,30,NaN,NaN,No,NaN,158.0,Cash,13.0,4.1,4.0
2,30-07-2024,Success,Prime SUV,Sahakar Nagar,Varthur,238,130,NaN,NaN,No,NaN,386.0,UPI,40.0,4.2,4.8
3,22-07-2024,Canceled by Customer,eBike,HSR Layout,Vijayanagar,0,0,Driver is not moving towards pickup location,NaN,NaN,NaN,384.0,NaN,0.0,NaN,NaN
4,02-07-2024,Success,Mini,Rajajinagar,Chamarajpet,252,80,NaN,NaN,No,NaN,822.0,Credit Card,45.0,4.0,3.0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 16 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        40539 non-null   object
 1   Booking_Status              40539 non-null   object
 2   Vehicle_Type                40539 non-null   object
 3   Pickup_Location             40539 non-null   object
 4   Drop_Location               40539 non-null   object
 5   V_TAT                       103024 non-null  int64
 6   C_TAT                       103024 non-null  int64
 7   Canceled_Rides_by_Customer  4079 non-null    object
 8   Canceled_Rides_by_Driver    7212 non-null    object
 9   Incomplete_Rides            87692 non-null   object
 10  Incomplete_Rides_Reason     1542 non-null    object
 11  Booking_Value               40539 non-null   float64
 12  Payment_Method              87692 non-null   object
 13  Ride_Distance               40539 non-null   float64
 14  Driver_Ratings              25207 non-null   float64
 15  Customer_Rating             25207 non-null   float64
dtypes: float64(4), int64(2), object(10)
memory usage: 12.6+ MB

In [17]:
df.isnull().sum()

Date                          62485
Booking_Status                62485
Vehicle_Type                  62485
Pickup_Location               62485
Drop_Location                 62485
V_TAT                             0
C_TAT                             0
Canceled_Rides_by_Customer        0
Canceled_Rides_by_Driver          0
Incomplete_Rides                  0
Incomplete_Rides_Reason           0
Booking_Value                 62485
Payment_Method                    0
Ride_Distance                 62485
Driver_Ratings                62485
Customer_Rating               62485
dtype: int64

In [5]:
df['Driver_Ratings'] = df.groupby('Vehicle_Type')['Driver_Ratings'].transform(lambda x : x.fillna(x.median()))

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103024 entries, 0 to 103023
Data columns (total 16 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   Date                        40539 non-null   object
 1   Booking_Status              40539 non-null   object
 2   Vehicle_Type                40539 non-null   object
 3   Pickup_Location             40539 non-null   object
 4   Drop_Location               40539 non-null   object
 5   V_TAT                       103024 non-null  int64
 6   C_TAT                       103024 non-null  int64
 7   Canceled_Rides_by_Customer  4079 non-null    object
 8   Canceled_Rides_by_Driver    7212 non-null    object
 9   Incomplete_Rides            87692 non-null   object
 10  Incomplete_Rides_Reason     1542 non-null    object
 11  Booking_Value               40539 non-null   float64
 12  Payment_Method              87692 non-null   object
 13  Ride_Distance               40539 non-null   float64
 14  Driver_Ratings              40539 non-null   float64
 15  Customer_Rating             25207 non-null   float64
dtypes: float64(4), int64(2), object(10)
memory usage: 12.6+ MB

In [6]:
df['Customer_Rating'] = df.groupby('Vehicle_Type')['Customer_Rating'].transform(lambda x : x.fillna(x.median()))

In [7]:
df.head()

,Date,Booking_Status,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
0,26-07-2024,Canceled by Driver,Prime Sedan,Tumkur Road,RT Nagar,0,0,NaN,Personal & Car related issue,NaN,NaN,444.0,NaN,0.0,4.0,4.0
1,25-07-2024,Success,Bike,Magadi Road,Varthur,203,30,NaN,NaN,No,NaN,158.0,Cash,13.0,4.1,4.0
2,30-07-2024,Success,Prime SUV,Sahakar Nagar,Varthur,238,130,NaN,NaN,No,NaN,386.0,UPI,40.0,4.2,4.8
3,22-07-2024,Canceled by Customer,eBike,HSR Layout,Vijayanagar,0,0,Driver is not moving towards pickup location,NaN,NaN,NaN,384.0,NaN,0.0,4.0,4.0
4,02-07-2024,Success,Mini,Rajajinagar,Chamarajpet,252,80,NaN,NaN,No,NaN,822.0,Credit Card,45.0,4.0,3.0

In [8]:
df.head()

,Date,Booking_Status,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
0,26-07-2024,Canceled by Driver,Prime Sedan,Tumkur Road,RT Nagar,0,0,NaN,Personal & Car related issue,NaN,NaN,444.0,NaN,0.0,4.0,4.0
1,25-07-2024,Success,Bike,Magadi Road,Varthur,203,30,NaN,NaN,No,NaN,158.0,Cash,13.0,4.1,4.0
2,30-07-2024,Success,Prime SUV,Sahakar Nagar,Varthur,238,130,NaN,NaN,No,NaN,386.0,UPI,40.0,4.2,4.8
3,22-07-2024,Canceled by Customer,eBike,HSR Layout,Vijayanagar,0,0,Driver is not moving towards pickup location,NaN,NaN,NaN,384.0,NaN,0.0,4.0,4.0
4,02-07-2024,Success,Mini,Rajajinagar,Chamarajpet,252,80,NaN,NaN,No,NaN,822.0,Credit Card,45.0,4.0,3.0

In [9]:
df['Customer_Rating'] = df.groupby('Vehicle_Type')['Customer_Rating'].transform(lambda x : x.fillna(x.median()))
df.head()

,Date,Booking_Status,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
0,26-07-2024,Canceled by Driver,Prime Sedan,Tumkur Road,RT Nagar,0,0,NaN,Personal & Car related issue,NaN,NaN,444.0,NaN,0.0,4.0,4.0
1,25-07-2024,Success,Bike,Magadi Road,Varthur,203,30,NaN,NaN,No,NaN,158.0,Cash,13.0,4.1,4.0
2,30-07-2024,Success,Prime SUV,Sahakar Nagar,Varthur,238,130,NaN,NaN,No,NaN,386.0,UPI,40.0,4.2,4.8
3,22-07-2024,Canceled by Customer,eBike,HSR Layout,Vijayanagar,0,0,Driver is not moving towards pickup location,NaN,NaN,NaN,384.0,NaN,0.0,4.0,4.0
4,02-07-2024,Success,Mini,Rajajinagar,Chamarajpet,252,80,NaN,NaN,No,NaN,822.0,Credit Card,45.0,4.0,3.0

In [10]:
df['Payment_Method'] = df['Payment_Method'].fillna('Cash')
df.head()

,Date,Booking_Status,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
0,26-07-2024,Canceled by Driver,Prime Sedan,Tumkur Road,RT Nagar,0,0,NaN,Personal & Car related issue,NaN,NaN,444.0,Cash,0.0,4.0,4.0
1,25-07-2024,Success,Bike,Magadi Road,Varthur,203,30,NaN,NaN,No,NaN,158.0,Cash,13.0,4.1,4.0
2,30-07-2024,Success,Prime SUV,Sahakar Nagar,Varthur,238,130,NaN,NaN,No,NaN,386.0,UPI,40.0,4.2,4.8
3,22-07-2024,Canceled by Customer,eBike,HSR Layout,Vijayanagar,0,0,Driver is not moving towards pickup location,NaN,NaN,NaN,384.0,Cash,0.0,4.0,4.0
4,02-07-2024,Success,Mini,Rajajinagar,Chamarajpet,252,80,NaN,NaN,No,NaN,822.0,Credit Card,45.0,4.0,3.0

In [11]:
df['Incomplete_Rides_Reason'] = df['Incomplete_Rides_Reason'].fillna('No')
df['Incomplete_Rides'] = df['Incomplete_Rides'].fillna('No')
df.head()

,Date,Booking_Status,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
0,26-07-2024,Canceled by Driver,Prime Sedan,Tumkur Road,RT Nagar,0,0,NaN,Personal & Car related issue,No,No,444.0,Cash,0.0,4.0,4.0
1,25-07-2024,Success,Bike,Magadi Road,Varthur,203,30,NaN,NaN,No,No,158.0,Cash,13.0,4.1,4.0
2,30-07-2024,Success,Prime SUV,Sahakar Nagar,Varthur,238,130,NaN,NaN,No,No,386.0,UPI,40.0,4.2,4.8
3,22-07-2024,Canceled by Customer,eBike,HSR Layout,Vijayanagar,0,0,Driver is not moving towards pickup location,NaN,No,No,384.0,Cash,0.0,4.0,4.0
4,02-07-2024,Success,Mini,Rajajinagar,Chamarajpet,252,80,NaN,NaN,No,No,822.0,Credit Card,45.0,4.0,3.0

In [12]:
df['Canceled_Rides_by_Driver'] = df['Canceled_Rides_by_Driver'].fillna('No')
df['Canceled_Rides_by_Customer'] = df['Canceled_Rides_by_Customer'].fillna('No')

df.head()

,Date,Booking_Status,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,Canceled_Rides_by_Customer,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating
0,26-07-2024,Canceled by Driver,Prime Sedan,Tumkur Road,RT Nagar,0,0,No,Personal & Car related issue,No,No,444.0,Cash,0.0,4.0,4.0
1,25-07-2024,Success,Bike,Magadi Road,Varthur,203,30,No,No,No,No,158.0,Cash,13.0,4.1,4.0
2,30-07-2024,Success,Prime SUV,Sahakar Nagar,Varthur,238,130,No,No,No,No,386.0,UPI,40.0,4.2,4.8
3,22-07-2024,Canceled by Customer,eBike,HSR Layout,Vijayanagar,0,0,Driver is not moving towards pickup location,No,No,No,384.0,Cash,0.0,4.0,4.0
4,02-07-2024,Success,Mini,Rajajinagar,Chamarajpet,252,80,No,No,No,No,822.0,Credit Card,45.0,4.0,3.0

In [13]:
df.isnull().sum()

Date                          62485
Booking_Status                62485
Vehicle_Type                  62485
Pickup_Location               62485
Drop_Location                 62485
V_TAT                             0
C_TAT                             0
Canceled_Rides_by_Customer        0
Canceled_Rides_by_Driver          0
Incomplete_Rides                  0
Incomplete_Rides_Reason           0
Booking_Value                 62485
Payment_Method                    0
Ride_Distance                 62485
Driver_Ratings                62485
Customer_Rating               62485
dtype: int64

In [14]:
df['Driver_Ratings'].value_counts()

Driver_Ratings
4.0    16548
4.1     1339
4.2     1301
4.4     1296
3.3     1289
3.8     1284
4.5     1283
3.1     1278
3.9     1272
3.7     1267
4.7     1264
3.5     1262
4.8     1258
3.4     1247
3.2     1246
4.9     1228
4.3     1228
3.6     1217
4.6     1207
3.0      629
5.0      596
Name: count, dtype: int64

In [15]:
# Connecting with the MYSql
from sqlalchemy import create_engine
from urllib.parse import quote_plus

# Here we use quote_plus because in my password there is @ which in sqlalchemy is reserved keyword.
password = quote_plus("SamyAk@24kocH") 


engine = create_engine(f"mysql+pymysql://root:{password}@localhost:3306/ola")

# Table_name = 'Customer_data'
df.to_sql('customer_data',con=engine , if_exists='replace', index=False)


print('Sucess')

Sucess